name: Build Branch
on: workflow_dispatch

jobs:
  build_all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        path: app
    - uses: actions/setup-node@master
      with:
        node-version: 19
    - name: Install Node dependencies
      run: |
        cd app
        npm install

    - name: Build
      run: |
        cd app
        npm run build
        echo "executing ls out on the directory:"
        ls out
